# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The x86 Blog
email: neerajx86@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  A Computer is an instrument whose music is ideas
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://x86.rocks" # the base hostname & protocol for your site
twitter_username: n4j
github_username:  n4j

# Build settings
#markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  
gems:
  - jekyll-coffeescript
  - jekyll-paginate